local notes = require("src.utils.bgm.notes")

local title = {
	melody = {
		{ freq = notes.E4, duration = 0.5 },
		{ freq = notes.G4, duration = 0.5 },
		{ freq = notes.B4, duration = 0.75 },
		{ freq = notes.A4, duration = 0.25 },
		{ freq = notes.G4, duration = 0.5 },
		{ freq = notes.E4, duration = 0.5 },
		{ freq = notes.D4, duration = 1 },
		{ freq = notes.REST, duration = 0.5 },
		{ freq = notes.F4, duration = 0.5 },
		{ freq = notes.A4, duration = 0.5 },
		{ freq = notes.C5, duration = 0.75 },
		{ freq = notes.B4, duration = 0.25 },
		{ freq = notes.A4, duration = 0.5 },
		{ freq = notes.F4, duration = 0.5 },
		{ freq = notes.E4, duration = 1 },
		{ freq = notes.REST, duration = 0.5 },
		{ freq = notes.G4, duration = 0.5 },
		{ freq = notes.B4, duration = 0.5 },
		{ freq = notes.D5, duration = 0.75 },
		{ freq = notes.C5, duration = 0.25 },
		{ freq = notes.B4, duration = 0.5 },
		{ freq = notes.G4, duration = 0.5 },
		{ freq = notes.F4, duration = 1 },
		{ freq = notes.REST, duration = 0.5 },
		{ freq = notes.E4, duration = 0.5 },
		{ freq = notes.G4, duration = 0.5 },
		{ freq = notes.C5, duration = 0.75 },
		{ freq = notes.B4, duration = 0.25 },
		{ freq = notes.A4, duration = 0.5 },
		{ freq = notes.G4, duration = 0.5 },
		{ freq = notes.F4, duration = 0.5 },
		{ freq = notes.E4, duration = 0.5 },
		{ freq = notes.D4, duration = 1 },
		{ freq = notes.REST, duration = 0.75 },
		{ freq = notes.G3, duration = 0.25 },
		{ freq = notes.C4, duration = 0.5 },
		{ freq = notes.E4, duration = 0.5 },
		{ freq = notes.G4, duration = 0.75 },
		{ freq = notes.F4, duration = 0.25 },
		{ freq = notes.E4, duration = 0.5 },
		{ freq = notes.C4, duration = 0.5 },
		{ freq = notes.B3, duration = 1 },
		{ freq = notes.REST, duration = 0.5 },
		{ freq = notes.D4, duration = 0.5 },
		{ freq = notes.F4, duration = 0.5 },
		{ freq = notes.A4, duration = 0.75 },
		{ freq = notes.G4, duration = 0.25 },
		{ freq = notes.F4, duration = 0.5 },
		{ freq = notes.D4, duration = 0.5 },
		{ freq = notes.C4, duration = 1.5 },
		{ freq = notes.REST, duration = 1 },
	},

	bassline = {
		{ freq = notes.C3, duration = 0.5 },
		{ freq = notes.G3, duration = 0.5 },
		{ freq = notes.D3, duration = 0.5 },
		{ freq = notes.A3, duration = 0.5 },
		{ freq = notes.E3, duration = 0.5 },
		{ freq = notes.B3, duration = 0.5 },
		{ freq = notes.C3, duration = 0.5 },
		{ freq = notes.G3, duration = 0.5 },
	},
}

return title
